include:
  - local: '.common-ci.yml'

stages:
  - build
  - test
  - deploy

# A base step for defining integration tests.
.integration:
  allow_failure: true
  stage: test
  variables:
    VERSION: "${CI_COMMIT_SHA}"
    IMAGE: "${IMAGE_NAME}"
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]tests?\]/i
    - $SKIP_TESTS
  before_script:
    - apk add make bash jq
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker pull "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${TARGET}"
    - docker tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${TARGET}" "${IMAGE_NAME}:${VERSION}-${TARGET}"
  script:
    - make test-${TARGET}

integration-ubuntu16:
  extends:
    - .integration
    - .target-ubuntu16
  variables:
    SKIP_TESTS: "true"

integration-ubuntu18:
  extends:
    - .integration
    - .target-ubuntu18

integration-ubi8:
  extends:
    - .integration
    - .target-ubi8
  variables:
    SKIP_TESTS: "true"
