include:
  - local: '.common-ci.yml'

stages:
  - image
  - lint
  - build
  - test
  - deploy
  - release

.dev-image:
  variables:
    BUILDIMAGE: ${CI_REGISTRY_IMAGE}/build
    IMAGE_TAG: ${CI_COMMIT_SHA}

build-dev-image:
  extends:
    - .dev-image
  stage: image
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - apk --no-cache add make
    - make .build-image
    - make .push-build-image

.requires-build-image:
  extends:
    - .dev-image
  variables:
    SKIP_IMAGE_BUILD: "yes"
  before_script:
    - apk --no-cache add make
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - make .pull-build-image

.lint:
  extends:
    - .requires-build-image
  stage: lint
  allow_failure: true

fmt:
  extends:
    - .lint
  script:
    - make docker-assert-fmt

vet:
  extends:
    - .lint
  script:
    - make docker-vet

lint:
  extends:
    - .lint
  script:
    - make docker-lint

build:
  extends:
    - .requires-build-image
  stage: build
  script:
    - make docker-build

unit-tests:
  extends:
    - .requires-build-image
  stage: test
  script:
    - make docker-coverage

# A base step for defining integration tests.
.integration:
  stage: test
  variables:
    VERSION: "${CI_COMMIT_SHA}"
    IMAGE: "${IMAGE_NAME}"
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]tests?\]/i
    - $SKIP_TESTS
  before_script:
    - apk add make bash jq
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker pull "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${TARGET}"
    - docker tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${TARGET}" "${IMAGE_NAME}:${VERSION}-${TARGET}"
  script:
    - make test-${TARGET}

.test:toolkit:
  extends:
    - .integration
  variables:
    TEST_CASES: "toolkit"

.test:docker:
  extends:
    - .integration
  variables:
    TEST_CASES: "docker"

.test:containerd:
  # TODO: The containerd tests fail due to issues with SIGHUP.
  # Until this is resolved with retry up to twice and allow failure here.
  retry: 2
  allow_failure: true
  extends:
    - .integration
  variables:
    TEST_CASES: "containerd"

.test:crio:
  extends:
    - .integration
  variables:
    TEST_CASES: "crio"

integration-ubuntu16:
  extends:
    - .integration
    - .target-ubuntu16
  variables:
    SKIP_TESTS: "true"

integration:toolkit-ubuntu18:
  extends:
    - .test:toolkit
    - .target-ubuntu18

integration:docker-ubuntu18:
  extends:
    - .test:docker
    - .target-ubuntu18

integration:containerd-ubuntu18:
  extends:
    - .test:containerd
    - .target-ubuntu18

integration:crio-ubuntu18:
  extends:
    - .test:crio
    - .target-ubuntu18

integration-ubi8:
  extends:
    - .integration
    - .target-ubi8
  variables:
    SKIP_TESTS: "true"
