include:
  - local: '.common-ci.yml'

stages:
  - build
  - test
  - deploy
  - release

# A base step for defining integration tests.
.integration:
  stage: test
  variables:
    VERSION: "${CI_COMMIT_SHA}"
    IMAGE: "${IMAGE_NAME}"
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]tests?\]/i
    - $SKIP_TESTS
  before_script:
    - apk add make bash jq
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker pull "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${TARGET}"
    - docker tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${TARGET}" "${IMAGE_NAME}:${VERSION}-${TARGET}"
  script:
    - make test-${TARGET}

.test:toolkit:
  extends:
    - .integration
  variables:
    TEST_CASES: "toolkit"

.test:docker:
  extends:
    - .integration
  variables:
    TEST_CASES: "docker"

.test:containerd:
  # TODO: The containerd tests fail due to issues with SIGHUP.
  # Until this is resolved with retry up to twice and allow failure here.
  retry: 2
  allow_failure: true
  extends:
    - .integration
  variables:
    TEST_CASES: "containerd"

.test:crio:
  extends:
    - .integration
  variables:
    TEST_CASES: "crio"

integration-ubuntu16:
  extends:
    - .integration
    - .target-ubuntu16
  variables:
    SKIP_TESTS: "true"

integration:toolkit-ubuntu18:
  extends:
    - .test:toolkit
    - .target-ubuntu18

integration:docker-ubuntu18:
  extends:
    - .test:docker
    - .target-ubuntu18

integration:containerd-ubuntu18:
  extends:
    - .test:containerd
    - .target-ubuntu18

integration:crio-ubuntu18:
  extends:
    - .test:crio
    - .target-ubuntu18

integration-ubi8:
  extends:
    - .integration
    - .target-ubi8
  variables:
    SKIP_TESTS: "true"
