---
##
## Variables that control where build artifacts are places for scanning and testing:
## CI_REGISTRY
## CI_REGISTRY_IMAGE
## CI_REGISTRY_USER
## CI_REGISTRY_PASSWORD
##
## Variables that control where release artifacts go:
## NGC_REGISTRY
## NGC_REGISTRY_IMAGE
## NGC_REGISTRY_USER
## NGC_REGISTRY_TOKEN
## REGISTRY_TOKEN
## REGISTRY_USER
## REGISTRY_IMAGE
##

default:
  image: docker:stable
  services:
    - docker:stable-dind
  tags:
    - type/docker
    - docker/privileged
    - cnt
    - container-dev
    - os/linux

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  # this is used because CI_PROJECT_NAME is not the same
  # as the image name used for this project
  IMAGE_NAME: "container-toolkit"

stages:
  - build
  - test
  - scan
  - deploy
  - release

.builddep_setup: &builddep_setup
  - apk add --no-cache bash findutils libmagic curl make git

.testdep_setup: &testdep_setup
  - apk add --no-cache bash make perl

.python_setup: &python_setup
  - apk add --no-cache python3 python3-dev py3-pip py3-wheel

.ci_login_setup: &ci_login_setup
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

# tags pulled images with $CI_PROJECT_NAME to work-around issue with contamer's support for local scans.
.pull_images: &pull_images
  - docker pull "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu16.04"
  - docker pull "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu18.04"
  - docker tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu16.04" "${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu16.04"
  - docker tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu18.04" "${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu18.04"

# Assumes ${OUT_IMAGE} is defined
.tag_images: &tag_images
  - docker tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu16.04" "${OUT_IMAGE}:${CI_COMMIT_TAG#v}-ubuntu16.04"
  - docker tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu18.04" "${OUT_IMAGE}:${CI_COMMIT_TAG#v}-ubuntu18.04"

.build_action: &build_action
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_SHA}" all
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_SHA}" push
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_SHA}" push-short
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_SHA}" push-latest

.test_action: &test_action
  - "true"

.deploy_action: &deploy_action
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_SHA}" push
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_SHA}" push-short
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_SHA}" push-latest

.deploy_tag_action: &deploy_tag_action
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_TAG#v}" push
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_TAG#v}" push-short
  - make IMAGE="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}" VERSION="${CI_COMMIT_TAG#v}" push-latest

# contamer does not support local scans on images that contain a port number
.scan_action: &scan_action
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-master.nvidia.com/sectooling/scanning/contamer.git
  - cd contamer
  - pip3 install -r requirements.txt
  - python3 contamer.py -ls --fail-on-non-os ${CONTAMER_SUPPRESS_VULNS:+--suppress-vulns ${CONTAMER_SUPPRESS_VULNS}} -- "${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu16.04"
  - python3 contamer.py -ls --fail-on-non-os ${CONTAMER_SUPPRESS_VULNS:+--suppress-vulns ${CONTAMER_SUPPRESS_VULNS}} -- "${IMAGE_NAME}:${CI_COMMIT_SHA}-ubuntu18.04"

.release_ngc_action: &release_ngc_action
  - make IMAGE="${NGC_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_TAG#v}" push
  - make IMAGE="${NGC_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_TAG#v}" push-short
  - make IMAGE="${NGC_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_TAG#v}" push-latest

.release_dockerhub_action: &release_dockerhub_action
  - make IMAGE="${REGISTRY_IMAGE}" VERSION="${CI_COMMIT_TAG#v}" push
  - make IMAGE="${REGISTRY_IMAGE}" VERSION="${CI_COMMIT_TAG#v}" push-short
  - make IMAGE="${REGISTRY_IMAGE}" VERSION="${CI_COMMIT_TAG#v}" push-latest

build:
  stage: build
  script:
    - *builddep_setup
    - *ci_login_setup
    - *build_action

test:
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]tests?\]/i
    - $SKIP_TESTS
  script:
    - *testdep_setup
    - *test_action

scan:
  stage: scan
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]scans?\]/i
    - $SKIP_SCANS
  script:
    - *builddep_setup
    - *python_setup
    - *ci_login_setup
    - *pull_images
    - *scan_action

deploy:sha:
  stage: deploy
  script:
    - *builddep_setup
    - *ci_login_setup
    - *pull_images
    - *deploy_action

deploy:tag:
  stage: deploy
  only:
    - tags
  variables:
    OUT_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}
  script:
    - *builddep_setup
    - *ci_login_setup
    - *pull_images
    - *tag_images
    - *deploy_tag_action

release:ngc:
  stage: release
  only:
    - tags
  variables:
    OUT_IMAGE: ${NGC_REGISTRY_IMAGE}
  script:
    - 'echo Commit Tag: $CI_COMMIT_TAG ; [[ -n "$CI_COMMIT_TAG" ]] || exit 1'
    - *builddep_setup
    - *ci_login_setup
    - *pull_images
    - *tag_images
    - docker login -u "${NGC_REGISTRY_USER}" -p "${NGC_REGISTRY_TOKEN}" "${NGC_REGISTRY}"
    - *release_ngc_action
  dependencies:
    - deploy:tag

release:dockerhub:
  stage: release
  only:
    - tags
  variables:
    OUT_IMAGE: ${REGISTRY_IMAGE}
  script:
    - 'echo Commit Tag: $CI_COMMIT_TAG ; [[ -n "$CI_COMMIT_TAG" ]] || exit 1'
    - *builddep_setup
    - *ci_login_setup
    - *pull_images
    - *tag_images
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"
    - *release_dockerhub_action
  dependencies:
    - deploy:tag
