# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:20.04 as build

RUN apt-get update && apt-get install -y --no-install-recommends \
        g++ \
        ca-certificates \
        wget && \
    rm -rf /var/lib/apt/lists/*

ENV GOLANG_VERSION 1.15.5
RUN wget -nv -O - https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-amd64.tar.gz \
    | tar -C /usr/local -xz
ENV PATH /usr/local/go/bin:$PATH

WORKDIR /work
COPY src/. .

RUN go build -o nvidia-toolkit run.go
RUN go build -o containerd containerd.go
RUN rm -rf go.* && \
    rm -rf *.go && \
    rm -rf vendor

FROM nvidia/cuda:11.0-base-ubuntu16.04

ENV NVIDIA_DISABLE_REQUIRE="true"
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=utility

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    jq \
    software-properties-common

RUN curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add - && \
    curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu16.04/nvidia-docker.list | \
        tee /etc/apt/sources.list.d/nvidia-docker.list

ARG LIBNVIDIA_CONTAINER_VERSION
ARG NVIDIA_CONTAINER_TOOLKIT_VERSION
ARG NVIDIA_CONTAINER_RUNTIME_VERSION

RUN apt-get update && apt-get install -y --no-install-recommends \
    libnvidia-container1=${LIBNVIDIA_CONTAINER_VERSION}-1 \
    libnvidia-container-tools=${LIBNVIDIA_CONTAINER_VERSION}-1 \
    nvidia-container-toolkit=${NVIDIA_CONTAINER_TOOLKIT_VERSION}-1 \
    nvidia-container-runtime=${NVIDIA_CONTAINER_RUNTIME_VERSION}-1

WORKDIR /work

COPY --from=build /work /work

RUN ln -s /work/toolkit.sh toolkit && \
	ln -s /work/crio.sh crio && \
	ln -s /work/docker.sh docker

ENV PATH=/work:$PATH

ARG VERSION

LABEL io.k8s.display-name="NVIDIA Container Runtime Config"
LABEL name="NVIDIA Container Runtime Config"
LABEL vendor="NVIDIA"
LABEL version="${VERSION}"
LABEL release="N/A"
LABEL summary="Automatically Configure your Container Runtime for GPU support."
LABEL description="See summary"

COPY ./LICENSE /licenses/LICENSE

ENTRYPOINT ["nvidia-toolkit"]
